jwt:
  secret: scc9811.secretKey
spring:
  datasource:
    url: jdbc:mariadb://호스트:포트/데이터베이스이름
    username: aaa
    password: aaa
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
